FROM ubuntu 
RUN apt-get update 
RUN DEBIAN_FRONTED ="noninteractive" apt-get -y install tzdata
RUN apt-get-y install apache2 
ADD . /var/www/html
RUN apt-get clean 
ENTRYPOINT apache2ctl -D FOREGROUND
ENV name Intellipat
